### ISSUE TITLE
ykcs11 does not derive Management Key from PIN

### ISSUE THREAD

**Issue by MichaelGrafnetter** [Yubico/yubico-piv-tool#110]
When I set "Use PIN as key" using the PIV Tool, I cannot login to PKCS11 as CKU_SO with PIN.

The problem probably lies in COMMON_token_login, which calls ykpiv_hex_decode without checking pin_len first and trying to derive the management key when it is too short.

**Comment by qpernil** [comment]
Key derivation has been deprecated, and is replaced with a mechanism that stores a random management key in one of the PIN-protected slots on the device. We are considering implementing this feature in the next minor release of yubico-piv-tool.

**Comment by qpernil** [comment]
ykcs11 now supports PIN-protected management keys on the master branch. This will be part of the 2.0.1 release. To use it, simply specify the normal pin as the SO PIN. If the device is configured with a PIN-protected management key it will be used, otherwise it will fail. Please note that a PIN try will be used up even if the device is not configured with PIN-protected management keys in the current implementation.
