### ISSUE TITLE
PIN-keys available over NFC

### ISSUE THREAD

**Issue by jas4711** [Yubico/yubico-piv-tool#15]
NIST 800-73-3 and FIPS 201, allow some operations over NFS but not not all.NIST 800-73-3 part 2 After table 2. says: "Note: Cryptographic protocols using private/secret keys requiring “PIN” security condition shall not be used on the contactless interface."

We currently don't follow this, allowing "PIN" keys even over contactless.  It isn't really clear whether we should fix this or not (it can be seen as a feature), but let's have an issue open around this until we decide.

**Comment by mouse07410** [comment]
I would keep it as a feature, for now. If you want to be really nice, make it a configuration option - whether to allow NFC access to PIV certs or not. Then it could be disabled if needed, or used if wanted.


On Feb 5, 2015, at 7:50 , Simon Josefsson <notifications@github.com<mailto:notifications@github.com>> wrote:


NIST 800-73-3 and FIPS 201, allow some operations over NFS but not not all.NIST 800-73-3 part 2 After table 2. says: "Note: Cryptographic protocols using private/secret keys requiring “PIN” security condition shall not be used on the contactless interface."

We currently don't follow this, allowing "PIN" keys even over contactless. It isn't really clear whether we should fix this or not (it can be seen as a feature), but let's have an issue open around this until we decide.

—
Reply to this email directly or view it on GitHub<https://github.com/Yubico/yubico-piv-tool/issues/15>.

--
Uri Blumenthal
uri@mit.edu<mailto:uri@mit.edu>

**Comment by mouse07410** [comment]
Just realized - I don't know of any application that can use PIV applet over NFC. Could you please tell me which email client or web browser can do it? Or another app type...?

Thanks!

**Comment by ryanchapman** [comment]
@mouse07410 if you use a USB reader that includes a contactless reader (one is the Gemalto IDBridge CL3000) and lay the Yubikey NEO on top of it, all commands work over the contactless interface.  For example, I'm able to generate a key with `yubico-piv-tool -r Gemalto -a generate -s 9a`.  Makes me also wonder if the wireless communications can be sniffed or if they are encrypted.

@jas4711 I think the danger is that someone could do a denial of service attack by sending commands over the contactless interface to block the PIN and then block the PUK, effectively rendering the keypairs on the device useless.  Unfortunately, that would mean the PIV applet would have to be reset and the keypairs re-generated.  So if I for instance was using the keypairs for ssh authentication, then I'm now locked out of ssh servers and would have to add the new public key to ~/.ssh/authorized_keys.  Let's hope I have a backup Yubikey NEO (where the backups pubkey was also in ~/.ssh/authorized_keys).

I would like to a see an option added to yubikey-piv-tool that makes the PIV applet NIST 800-73 compliant as far as the security data model.  That would apply the following restriction:
Contactless with no PIN: 
-allow read of: CHUID (0x3000), discovery object (0x6050), slot 9E
-allow write of: nothing
all other containers require contact interface.  Some require PIN. See NIST 800-73-4, section 3.5 for full listing of access rules.

**Comment by mouse07410** [comment]
> all commands work over the contactless interface. For example, I'm able to generate a key
> with `yubico-piv-tool -r Gemalto -a generate -s 9a`. 

Please, please! What application/drive/OS did you use to get through to the NEO? Just `yubico-piv-tool`? I'm on Mac, and I wasn't able to access the token through the USB-based NFC reader.

> Makes me also wonder if the wireless communications can be sniffed...

Not really, according to this:

> establish communication by bringing them within 10 cm (4 in) of each other

and 

> With a maximum working distance of less than 20 cm, NFC has a shorter range, which reduces the likelihood of unwanted interception. That makes NFC particularly suitable for crowded areas that complicate correlating a signal with its transmitting physical device (and by extension, its user).

[Wiki](https://en.wikipedia.org/wiki/Near_field_communication) says that the effective range is less that 20cm. Even with an amplified directional antenna, it isn't going to be practical to attack the token, I think - but keeping it in an insulated sleeve (like a credit card) would make sense anyway.

> ... or if they are encrypted.

From the same source:
> Secure communications are available by applying encryption algorithms as is done for Credit Card

Would somebody from Yubico please confirm or deny that NEO uses the (optional) encryption of the NFC communications (establishes "secure channel"), to avoid sniffing?


> the danger is that someone could do a denial of service attack by sending commands over
> the contactless interface to block the PIN and then block the PUK, effectively rendering the
> keypairs on the device useless

And how do you think such an attack could be carried out? 

In any case, protect when not in use.

**Comment by ryanchapman** [comment]
@mouse07410 The Gemalto reader I listed before can be purchased from their web store for about $75 incl. shipping to the U.S.  Might be cheaper elsewhere.  I can't remember if I had to install the Gemalto drivers for that reader, but I do have it working on Windows 8, Linux, and Mac OS X with tools like piv-tool, opensc-tool, and of course, yubico-piv-tool.  In the case of the yubico-piv-tool, you just have to provide the `-r Gemalto` option to select the reader because it looks for a reader that starts with `Yubikey` by default.

ISO14443A (contactless) communications can be sniffed; it's just a matter of if it is practical. The paper http://www.rfidblog.org.uk/Hancke-JoCSSpecialRFIDJune2010.pdf suggests that it is possible at distances greater than 4 inches.

Keeping the NEO in a protected sleeve doesn't adapt very well to the form factor--it is designed to go on a keychain.  If I was going to use sleeves, I might just go with a traditional PIV smart card, especially if I don't need the built-in USB interface and can use a smartcard reader instead.

For the PIN/PUK blocking attack, it's as simple as sending a few commands to the Yubikey NEO wirelessly:

```i=0; while [[ $i != 256 ]]; do yubico-piv-tool -v3 -a verify-pin -P 324234 -N 12345 2>&1 | grep "Pin code blocked" && break; i=$((i+1)); done; i=0; while [[ $i != 256 ]]; do yubico-piv-tool -a change-puk -P 3545410 -N 123456 2>&1 | grep "The puk code is blocked" && break; i=$((i+1)); done```

If you try that with a NEO laying on top of a Gemalto IDBridge CL3000 (so it's using the contactless interface of the NEO), you'll find that the PIV applet is now blocked and you must reset it with:
`yubico-piv-tool -a reset`.  You'll notice that the certs and private keys are gone because of the reset.

When I said I would like to see an option added to yubico-piv-tool to make the PIV applet NIST 800-73 compliant, I meant that the default should still be as things are today, with all containers accessible over the contactless interface.  I would just like the option to turn on NIST 800-73 compliance if the situation demands more security.  So it wouldn't effect you, unless you actually ran something like `yubico-piv-tool -a enable-nist-800-73` By the way, if NIST compliance was on, you could still perform PK operations using the key/cert in slot 9E, which NIST 800-73 makes accessible over the contactless interface without a PIN.

**Comment by mouse07410** [comment]
> For the PIN/PUK blocking attack, it's as simple as sending incorrect PIN/PUK verify code
> commands to the Yubikey NEO wirelessly

No-no-no, I understand **what** the attack is - I am asking **how** you're going to reach this device, especially if (a) you aren't within 20cm from it, and (b) it is in a sleeve (screw the form-factor :)?

> Keeping the NEO in a protected sleeve doesn't adapt very well to the form factor--it is designed
> to go on a keychain. If I was going to use sleeves, I might just go with a traditional PIV smart card, 
> especially if I don't need the built-in USB interface and can use a smartcard reader instead.

Well, I find that I can use an improvised sleeve conveniently enough. And the smart cards do not have the capabilities NEO offers... But I see your point.

> I do have it working on Windows 8, Linux, and Mac OS X with tools like piv-tool, opensc-tool, and of
> course, yubico-piv-tool. In the case of the yubico-piv-tool, you just have to provide the `-r Gemalto` 
> option to select the reader because it looks for a reader that starts with Yubikey by default.

**Thank you!**

> an option added to yubico-piv-tool to make the PIV applet NIST 800-73 compliant, I meant that the
> default should still be as things are today, with all containers accessible over the contactless
> interface. I would just like the option to turn on NIST 800-73 compliance if the situation demands
> more security

As an option (and not even a default setting), it wouldn't negatively affect my usage model, so my objection is removed. 

> if NIST compliance was on, you could still perform PK operations using the key/cert in slot 9E,
> which NIST 800-73 makes accessible over the contactless interface without a PIN.

Yeah, if I used NEO to unlock my doors, it would be important. :-)

As it is - my keys are strictly slot- and key-usage-conformant. That means Digital Signature key (with Email Security and Digital Signature usage allowed) usable for email signing and login, is in 9c and nowhere else. Similarly Key Management key is in 9d...

**Comment by ryanchapman** [comment]
I see your point.  If the NEO is in a sleeve, I believe an attack is not possible because the sleeve should prevent the NEO from being powered at all. And even if there isn't a sleeve, the attacker's antenna would have to be close to the NEO.  I'd be interested in what you're envisioning for a sleeve.  I might want to do the same thing.

And you are correct on the usage of 9E.  Certainly more secure to use the slots as they were intended.

**Comment by mouse07410** [comment]
> And even if there isn't a sleeve, the attacker's antenna would have to be close to the NEO.

While a really good directional antenna and a power amplifier could increase that distance somewhat, but still it isn't a very practical attack most of the time, IMHO. 

> I'd be interested in what you're envisioning for a sleeve. I might want to do the same thing.

Well, in my case I do carry smart cards in their special sleeves - so my NEO is in the same pocket, shielded by the sleeve not intended for it. :-)

It would be trivial to either make a sorta-sleeve from aluminum foil (bitchen/baking supplies), or re-use some of the smart card sleeves.

**Comment by mouse07410** [comment]
I found that I have `SCL3711-NFC&RW` contactless card reader. I got and installed the Mac OS X driver for it, but had no luck whatsoever:
- Neither OpenSC tools (`pkcs11-tool`, etc) nor `yubico-piv-tool` were able to recognize either the reader, or the Yubikey token placed on it.
- After I installed `ibnfc`, it could communicate with the NEO placed on the reader on the lowest (APDU) level, but it did not help the above utilities - they still don't work.

If you have any recommendation - I'm all ears. ;)

**Comment by ryanchapman** [comment]
@mouse07410 Kind of hard to say because I don't have that reader to test with.

Does `opensc-tool -l` return anything?  You have to get that working before yubico-piv-tool will be able to communicate through the reader.

On my Macbook with the Gemalto Prox-DU reader plugged in, I get back
```
ryan@Chapmans-Macbook-Pro:~$ opensc-tool -l
# Detected readers (pcsc)
Nr.  Card  Features  Name
0    No              Gemalto Prox Dual USB PC Link Reader(2)
1    Yes             Gemalto Prox Dual USB PC Link Reader(1)
```

Reader Nr 1 is the contactless interface and Nr 0 is the contact interface.

Now it's just a matter of telling yubico-piv-tool to use the contactless reader:

```
ryan@Chapmans-Macbook-Pro:~$ yubico-piv-tool -r "Gemalto Prox Dual USB PC Link Reader(1)" -a status
CHUID:	3019[...]00fe00
Slot 9a:
	Algorithm:	RSA2048
	Subject DN:	CN=joe, O=Test
	Issuer DN:	CN=joe, O=Test
	Fingerprint:	88[...]ce
	Not Before:	Feb  1 05:12:36 2016 GMT
	Not After:	Jan 31 05:12:36 2017 GMT
PIN tries left:	3
```

I also tested with a ACR122U-A9 reader I have and it works as well

```
ryan@Chapmans-Macbook-Pro:~$ opensc-tool -l
# Detected readers (pcsc)
Nr.  Card  Features  Name
0    Yes             ACS ACR122U PICC Interface
ryan@Chapmans-Macbook-Pro:~$ yubico-piv-tool -r "ACS ACR122U PICC Interface" -a status
CHUID:	3019[...]00fe00
Slot 9a:
	Algorithm:	RSA2048
	Subject DN:	CN=joe, O=Test
	Issuer DN:	CN=joe, O=Test
	Fingerprint:	88[...]ce
	Not Before:	Feb  1 05:12:36 2016 GMT
	Not After:	Jan 31 05:12:36 2017 GMT
PIN tries left:	3
```

**Comment by mouse07410** [comment]
On my MacBook Pro with SCR-3310 smart card reader **and** SCL-3711 NFC&RW contactless card reader, I get:
```
$ opensc-tool -l
# Detected readers (pcsc)
Nr.  Card  Features  Name
0    No              SCR3310 Smart Card Reader
$
```

Of course, removing the SCR gives me:
```
$ opensc-tool -l
No smart card readers found.
$
```

With a test-program built on `libnfc` I get (regardless of whether the SCR reader is present or not, and with NEO placed on top of the SCL-3711)
```
$ ./nfc-test uses libnfc libnfc-1.7.1-66-g24979c6
NFC reader: SCM Micro / SCL3711-NFC&RW opened
The following (NFC) ISO14443A tag was found:
    ATQA (SENS_RES): 00  44  
       UID (NFCID1): 04  15  32  32  5b  38  80  
      SAK (SEL_RES): 28  
          ATS (ATR): 78  f7  b1  02  59  75  62  69  6b  65  79  4e  45  4f  72  33  
$
```

**Comment by ryanchapman** [comment]
@mouse07410 Does placing the NEO in the reader's RF field and running `yubico-piv-tool -r "SCR3711" -a status` work?  If not, i'm at a loss since I don't have that reader and can't test it further.

**Comment by mouse07410** [comment]
> Does placing the NEO in the reader's RF field and running 
> `yubico-piv-tool -r "SCR3711" -a status` work?

Nope. I guess (and Ludovic says that too) that the reader I was (un)lucky to lay my hands on is not CCID-compliant. Therefore his library doesn't work with it - therefore OpenSC doesn't work with it, therefore `yubico-piv-tool` cannot work with it. :-(

I guess the only thing I can do it find a different reader, and give it a try...

**Comment by grandamp** [comment]
If you have Android, and would like to test interaction similar to the use of PIV (with the Card Authentication key and certificate) via NFC, give this a try: https://play.google.com/store/apps/details?id=com.idevity.card.read

If you enable the debug logging, you can see the APDUs and observe the private key proof of possession for CAK.

Source: https://github.com/grandamp/card-read

**Comment by mouse07410** [comment]
**Update**

Gemalto Prox-DU turned out to work very well with NEO over NFC. So that problem is solved. It would be nice to be able to use SCL3711, especially since I've got a few of them, but they don't work on Mac (no suitable driver, what can I say?).

Regarding Android - what I'm looking for is not a debugging tool, but an *application* - ideally an email client plugin like OpenKeychain, and a browser plugin that would make use of the PIV keys via NFC (because that's the only/main way to access hardware crypto tokens on Android).

**Comment by dschuermann** [comment]
I know this is an old thread, but still if anyone reads this:
We are working on PIV support for Android over NFC: https://hwsecurity.dev/piv/

If you have a specific project or requirement feel free to contact us.

**Comment by mouse07410** [comment]
First, two obvious requirements are plugins for email clients (something similar to OpenKeychain, but for PIV) and for Web browsers.

Second, as Apple now provides NFC interface on iPhones, I'd love to see PIV support for iOS (same requirements as above).

**Comment by qpernil** [comment]
This issues is old and isn't related to Yubico PIV tool so closing it.
