### ISSUE TITLE
Disable PIN for login

### ISSUE THREAD

**Issue by axeII** [Yubico/yubico-piv-tool#230]
Hi 👋 
is it possible to use yubikey as a Smart card but at the same time disable PIN Authorisation? 

Use case I am looking for is that when plug yubikey in I would be automatically logged in without entering PIN.

Cheers.

**Comment by a-dma** [comment]
I assume that you're interested in PIV since you're posting here.
In that case you can set different PIN policies when generating a key, including the "Never" policy.

More info at https://developers.yubico.com/PIV/Introduction/Yubico_extensions.html

You can set these with yubico-piv-tool or YubiKey Manager.

I hope that helps.

**Comment by qpernil** [comment]
Just a small clarification - PIV does not allow changing the PIN policy for an existing key. Also, by default the 9e slot is not PIN-protected (it uses the 'Never' policy by default).

I'm closing this issue as I believe it has been resolved. Don't hesitate to open a new issues if needed.
