### ISSUE TITLE
Changing amount of allowed PIN retries via piv tool on windows

### ISSUE THREAD

**Issue by dave7280** [Yubico/yubico-piv-tool#238]
Hi,

I'd like to change the number of allowed retries before PIN is locked via piv tool on windows (tested x86 and x64). 

* Is changing such lock-out threshold possible? 
* Or is it only changing the current counter value?

If so:

```
yubico-piv-tool.exe -a verify-pin -a pin-retries --pin-retries=10 --puk-retries=10

Enter PIN:
Retrieving PIN failed.
```

The PIN is being somehow validated as correct, as when i type incorrect one i get error message about counter being decreased.

Are there any limitations when we can change pin retries amount?

There's very little documentation around this. I stumbled only  upon this topic:
https://github.com/Yubico/yubico-piv-tool/issues/24 and based my command line parameters on it.

**Comment by qpernil** [comment]
Hi,

The error message indicates it failed to read a valid pin from std input, and thus it didn't attempt any operation om the YubiKey (and therefore didn't change the retry count).

The command you used is indeed the command used to change both PIN and PUK retries in one go. As a side effect this command will also reset the actual PIN and PUK (and retry counters) to default values, so you should set them again after using this command. In order to execute this command both PIN and MGMT KEY must be verified. If you don't specify the MGMT KEY the default one will be used, which will not work if you have changed it (as you definitely should have). To specify a MGMT KEY use the -k option.

Please see this link for more information on the actual command, and it's function. 
https://developers.yubico.com/PIV/Introduction/Yubico_extensions.html#_set_pin_retries

I'm closing this issue, please feel free to open it again if needed.
