### ISSUE TITLE
Support for writing (and reading) generic data objects

### ISSUE THREAD

**Issue by klali** [Yubico/yubico-piv-tool#31]
We should consider if it's worth adding to the tool to write and read generic data objects.

**Comment by Davidllo** [comment]
I think that you need to keep the tool as simple as possible - don't forget 99% of your customers just want to have a public/private key pair that logs them into a computer or website.  The OpenSc tools are where advanced users will already know to go for stuff like this...

See my other post about installing the mandatory files as described in SP800-73-4 by default though.

**Comment by mouse07410** [comment]
1. I think that yes we do want the tool to be able to write and read generic data objects.
2. I do **not** think that the majority of users can possibly want to "just" have a public/private key pair -  because such a pair would be utterly useless (_see Note below_) unless this key-pair is accessible by **standard applications**, such as (for example) Apple Mail and Safari on Mac. And for that to happen, the card **must** carry more than just a couple of key pairs. That's what being PIV-compliant means - providing the calling system with objects in addition to the key pairs.
3. At the  barest minimum the card should provide usable CCC and (signed) CHUID objects. 
4. I do think that the tool (_yubico-piv-tool_) should have a capability "-a initialize" that would generate and write to the card the minimal set of data objects that would make it PIV-compliant.

__Note__: There are applications (e.g. Firefox and Thunderbird) that can probably get away with having working __opensc-pkcs11.so__ library. Users for who that is enough, indeed may not need a PIV-compatible card. One could argue that for such users having an OpenPGP applet is more than sufficient.

**Comment by mouse07410** [comment]
1. What's the decision here? 
2. To what extent does `piv-tool` already do "writing and reading of generic data objects? 
3. Does Yubico envision use of their `yubico-piv-tool` on a platform for which OpenSC (and therefore `piv-tool`) are not available (cannot be built/installed with reasonable ease)?

**Comment by klali** [comment]
No decisions made on this, there's some code on a branch, if it seems useful for more than niche cases (or enough niche cases) it will probably be merged.
yubico-piv-tool contains features to make the piv functionality on a YubiKey easier to use, some of this is Yubico specific and some of it should work with any PIV implementation.

**Comment by ryanchapman** [comment]
@klali can this be merged into master so I don't have to keep distributing a custom compile to my users?

**Comment by klali** [comment]
This is already merged to master, but not released yet. I'll look at cutting a 1.3.0 with this in later today.
