### ISSUE TITLE
Yubikey does not allow multiple signs per session

### ISSUE THREAD

**Issue by cmouse** [Yubico/yubico-piv-tool#351]
Version: 2.0.0-2
Source: ubuntu

I am developing PKCS#11 interface usage. I was testing it with my Yubico key PIV applet, and found that is does not function correctly when doing repeated signing requests on a session.

Please see https://gist.github.com/cmouse/79fdd61bd74f0b1a80b5c7ce95ce2ab4 for the source code reproducing this issue.

Any ideas what I could be doing wrong or is this some firmware issue? This happens also with my older Yubikey NEO device.

When running it locally I see

```
$ ./test-pkcs11 yubico 0 02 12345678
C_Initialize
 IN: pInitArgs = NULL
C_Initialize = CKR_OK
C_Initialize
 IN: pInitArgs = NULL
C_Initialize = CKR_OK
C_GetSlotList
 IN: tokenPresent = CK_TRUE
 IN: pulCount = 0x7FFC70CEE4F8 = 140030664182304
 OUT: pSlotList = (1) NO-VALUES
C_GetSlotList = CKR_OK
C_GetSlotList
 IN: tokenPresent = CK_TRUE
 IN: pulCount = 0x7FFC70CEE4F8 = 1
 OUT: pSlotList = (1) [ SL0 ]
C_GetSlotList = CKR_OK
C_GetTokenInfo
 IN: slotID = SL0
 OUT: pInfo = {
 label: "YubiKey PIV #16847598 (https://support.yubico.com/hc/requests/16847598)"
 manufacturerID: "Yubico (www.yubico.com (http://www.yubico.com))"
 model: "YubiKey YK5"
 serialNumber: "16847598"
 flags: 1037 = CKF_RNG | CKF_LOGIN_REQUIRED | CKF_USER_PIN_INITIALIZED | CKF_TOKEN_INITIALIZED
 ulMaxSessionCount: 16
 ulSessionCount: 0
 ulMaxRwSessionCount: 16
 ulRwSessionCount: 0
 ulMaxPinLen: 48
 ulMinPinLen: 6
 ulTotalPublicMemory: 16
 ulFreePublicMemory: 16
 ulTotalPrivateMemory: 16
 ulFreePrivateMemory: 16
 ulFreePrivateMemory: 16
 hardwareVersion: 1.0
 firmwareVersion: 5.43
 utcTime:
 }
C_GetTokenInfo = CKR_OK
Module : yubico
Slot : 0
Label : YubiKey PIV #16847598 (https://support.yubico.com/hc/requests/16847598)
Manufacturer : Yubico (www.yubico.com (http://www.yubico.com))
Model : YubiKey YK5
Serial number: 16847598
C_OpenSession
 IN: slotID = SL0
 IN: flags = 6 = CKF_SERIAL_SESSION | CKF_RW_SESSION
 IN: pApplication = NULL
 IN: Notify = NULL
 OUT: phSession = 0x7FFC70CEE508 = S1
C_OpenSession = CKR_OK
C_Login
 IN: hSession = S1
 IN: userType = CKU_USER
 IN: pPin = (8) "12345678"
C_Login = CKR_OK
C_FindObjectsInit
 IN: hSession = S1
 IN: pTemplate = (2) [ CKA_CLASS, CKA_ID ]
C_FindObjectsInit = CKR_OK
C_FindObjects
 IN: hSession = S1
 IN: max_object_count = 1
 OUT: object = (1) [ H87 ]
C_FindObjects = CKR_OK
C_FindObjectsFinal
 IN: hSession = S1
C_FindObjectsFinal = CKR_OK
Input : the quick brown fox jumped over the lazy dog
C_DigestInit
 IN: hSession = S1
 IN: pMechanism = {
 mechanism: CKM_SHA256
 pParameter: (0) NULL
 }
C_DigestInit = CKR_OK
C_Digest
 IN: hSession = S1
 IN: pData = (44) "the quick brown fox jumped over the lazy dog"
 OUT: pDigest = (32) " \xC1\x89-\xF4\xE6efeX(\x93g\xAE\x16\x82\xD1\xF9;\xC5\xBE@Ibt\x92\xCD\xB5\xA4&5\xE4"
C_Digest = CKR_OK
C_SignInit
 IN: hSession = S1
 IN: pMechanism = {
 mechanism: CKM_ECDSA
 pParameter: (0) NULL
 }
 IN: hKey = H87
C_SignInit = CKR_OK
C_Sign
 IN: hSession = S1
 IN: pData = (32) " \xC1\x89-\xF4\xE6efeX(\x93g\xAE\x16\x82\xD1\xF9;\xC5\xBE@Ibt\x92\xCD\xB5\xA4&5\xE4"
 OUT: pSignature = (64) "\xE9\x15\x10\xB2\xE1P\xF29*D\xE5d<\xD8jMk^\xEB\xB8\xD0\x10\xFF\xAF\xB0\xEE\xEEjg\xE8\x94\x06ej\xBC\x91\x1E\x10$\x90\xF5..."
C_Sign = CKR_OK
Output : e91510b2e150f2392a44e5643cd86a4d6b5eebb8d010ffafb0eeee6a67e89406656abc911e102490f500748ae27850d8357ccb340c641582a14bfaa06e84efd3
C_DigestInit
 IN: hSession = S1
 IN: pMechanism = {
 mechanism: CKM_SHA256
 pParameter: (0) NULL
 }
C_DigestInit = CKR_OK
C_Digest
 IN: hSession = S1
 IN: pData = (44) "the quick brown fox jumped over the lazy dog"
 OUT: pDigest = (32) " \xC1\x89-\xF4\xE6efeX(\x93g\xAE\x16\x82\xD1\xF9;\xC5\xBE@Ibt\x92\xCD\xB5\xA4&5\xE4"
C_Digest = CKR_OK
C_SignInit
 IN: hSession = S1
 IN: pMechanism = {
 mechanism: CKM_ECDSA
 pParameter: (0) NULL
 }
 IN: hKey = H87
C_SignInit = CKR_OK
C_Sign
 IN: hSession = S1
 IN: pData = (32) " \xC1\x89-\xF4\xE6efeX(\x93g\xAE\x16\x82\xD1\xF9;\xC5\xBE@Ibt\x92\xCD\xB5\xA4&5\xE4"
C_Sign = CKR_USER_NOT_LOGGED_IN
C_Sign() failed: (0x101): No user has logged in 
```

**Comment by qpernil** [comment]
Hi;

pkcs11-tool shows the following for key id '02'

Private Key Object; RSA
label: Private key for Digital Signature
ID: 02
Usage: decrypt, sign
Access: always authenticate, sensitive, always sensitive, never extractable, local

The always authenticate access means you need to validate the PIN before each signature.
To re-authenticate you need to use C_Login(CKU_CONTEXT_SPECIFIC, ...) after calling C_SignInit (so there is an ongoing sign operation) and before C_Sign (or C_SignUpdate / C_SignFinal of you were useing those), which terminates the operation (except for particular situations, specifically if you get CKR_BUFFER_TOO_SMALL or if you send in NULL for the buffer, to get the required length).

Please note that PKCS#11 id 02 is the sign key is slot 9c in PIV. This mapping was chosen to be compatible with the id:s used by the opensc pkcs11 library.

Please also note that the access reported here is hard-coded in the library, not determined from the device. This will be correct unless you have used non-default PIN policy when importing or generating the key(s). The library assumes the defaults (specified by PIV) that says slot 9C is always-auth and the rest not.

You code should work with any other key ID.

If you look at source code for pkcs11-tool and others, they typically check the CKA_ALWAYS_AUTH attribute and do this re-auth if true. Another approach is to just react to this particular error code with a re-auth. If you are going to perform many sign operations a combined approach might be best where you 'learn' if you need to re-auth on the first attempt, and then keep doing the same. This would be to avoid the extra commands that are always going to fail (since every sign 'uses up' the pin verification).

For libykcs11 there is also a special case allowed if you want to create a key and then sign with it in the same pkcs11 session. To create or generate a key you need to log in as SO (which authenticates using the PIV admin key), but to sign you need to verify the PIN. You can do this by using the same C_Login(CKU_CONTEXT_SPECIFIC,...) when you have a SO session.

Best regards!

**Comment by cmouse** [comment]
Thank you! This helps alot.

**Comment by cmouse** [comment]
Ok - tested that this works. Many thanks for this!
