### ISSUE TITLE
Ubuntu package is broken

### ISSUE THREAD

**Issue by tamasd** [Yubico/yubico-piv-tool#376]
Hello,

I installed the `yubico-piv-tool` package from yubico's repository on ubuntu impish. When I try to launch it (with any parameters), I get the following error: `yubico-piv-tool: symbol lookup error: yubico-piv-tool: undefined symbol: ykpiv_set_mgmkey3`.

**Comment by qpernil** [comment]
This issue has come up lately, and is typically caused by an older libykpiv2 package being installed.  Try the following:
sudo apt purge libykpiv2
The PPA package includes a newer version if this library so the above should suffice.
The root cause is a dependency conflict between the ubuntu package libykpiv2 and the ppa-provided yubico-piv-tool.
This will be fixed in a later version.

**Comment by tamasd** [comment]
Thank you, it works now
