### ISSUE TITLE
Getting error "Unsupported parameters" when trying to sign with jarsigner and other java based tools.

### ISSUE THREAD

**Issue by TomasLoow** [Yubico/yubico-piv-tool#397]
Hello.

We're encountering a strange error when trying to sign data using an ec key from java based applications on some of our computers and would appreciate any help in solving or at least identifying the problem.  The weird part is that it works on one of my colleagues computer, but fails to work on mine and another colleagues PC. We've spent a lot of time trying to figure out the cause, checking that we run the same java version, same libykcs11 version and everything else we can think of without getting any wiser.

-----

Signing data using yubico-piv-tool works just fine, with for example 

`yubico-piv-tool -a verify-pin --sign -s 9c -H SHA384 -A ECCP384 -i foo.txt -o foo.txt.asc`

But I cannot get signing to work from any java based application that calls libykcs11.dll using the `sun.security.pkcs11` package. I get an exception saying "Unsupported parameters" in all cases I've tried.

```
jarsigner.exe -keystore NONE -storetype PKCS11 -providerClass sun.security.pkcs11.SunPKCS11 -providerArg .\pkcs11.cfg <path to .jar-file> "X.509 Certificate for Digital Signature"
Enter Passphrase for keystore:
jarsigner error: java.security.ProviderException: java.security.KeyStoreException: Unsupported parameters
```
It asks for the PIN as expected before failing.

I get the same error when trying to do it from java myself using a minimal test script.
```
Exception in thread "main" java.security.ProviderException: java.security.KeyStoreException: Unsupported parameters
        at jdk.crypto.cryptoki/sun.security.pkcs11.P11KeyStore.engineGetKey(P11KeyStore.java:331)
        at java.base/java.security.KeyStore.getKey(KeyStore.java:1050)
        at SimpleYubiTest.run(SimpleYubiTest.java:55)
        at SimpleYubiTest.main(SimpleYubiTest.java:67)
Caused by: java.security.KeyStoreException: Unsupported parameters
        at jdk.crypto.cryptoki/sun.security.pkcs11.P11KeyStore.loadPkey(P11KeyStore.java:1378)
        at jdk.crypto.cryptoki/sun.security.pkcs11.P11KeyStore.engineGetKey(P11KeyStore.java:316)
        ... 3 more
Caused by: java.io.IOException: Only named ECParameters supported
        at java.base/sun.security.util.ECParameters.engineInit(ECParameters.java:148)
        at java.base/java.security.AlgorithmParameters.init(AlgorithmParameters.java:311)
        at java.base/sun.security.util.ECUtil.getECParameterSpec(ECUtil.java:189)
        at jdk.crypto.cryptoki/sun.security.pkcs11.P11KeyStore.loadPkey(P11KeyStore.java:1374)
```

When stepping through my testscript, it seems like the root of the problem is that a java call to to libykcs11.dll, `token.p11.C_GetAttributeValue`, return broken nonsense data for `CKA_EC_PARAMS `. This then results in an exception with the message "java.io.IOException: Only named ECParameters supported" later in the process.

-----

We get the same problems using both OpenJDK 17 and 18.

The certificate is stored in slot 9C, it was loaded from an existing certificate using YubiKey Manager. The certificate uses signature algorithm **ecdsa-with-SHA384** and NIST CURVE: P-384

Do anyone have any suggestions as to what may be causing this error?

**Comment by qpernil** [comment]
Would you mind expanding on what data you get from CKA_EC_PARAMS ? In my tests that seems to work, you get EC parameters in the 'named curve OID' format.

**Comment by qpernil** [comment]
Also, Im curious @mouse07410 what problem exactly was it you thought was gone ? As far as I know ykcs11 reports CKA_ALWAYS_AUTHENTICATE properly, with the exception of for non-default policy imported keys on YubiKeys without metadata support.

**Comment by qpernil** [comment]
Another thing : How was that key put on the YUbiKey ? Generated or imported ? If imported, would you mind sharing how ? I.e. what tools were used etc.

**Comment by TomasLoow** [comment]
Thank you for taking time to look into this.

The key was imported using YubiKey manager. From the Applications > PIV > Certificates > Digital Signature view, I used the import button to import first the certificate and then the private key, both in PEM format.

When The value for CKA_EC_PARAMS I can see when stepping through Java code before it crashes is `CKA_EC_PARAMS = 30820157020101303c06072a8648ce3d0101023100fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeffffffff0000000000000000ffffffff307b0430fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeffffffff0000000000000000fffffffc0430b3312fa7e23ee7e4988e056be3f82d19181d9c6efe8141120314088f5013875ac656398d8a2ed19d2a85c8edd3ec2aef031500a335926aa319a27a1d00896a6773a4827acdac73046104aa87ca22be8b05378eb1c71ef320ad746e1d3b628ba79b9859f741e082542a385502f25dbf55296c3a545e3872760ab73617de4a96262c6f5d9e98bf9292dc29f8f41dbd289a147ce9da3113b5f0b8c00a60b1ce1d7e819d7a431d7c90ea0e5f023100ffffffffffffffffffffffffffffffffffffffffffffffffc7634d81f4372ddf581a0db248b0a77aecec196accc52973020101`

which is clearly the wrong length and all the "ffff..." and "0000..." streaks look highly suspicious as well.

**Comment by qpernil** [comment]
I think you might be getting explicit ec curve parameters, similar to https://github.com/Yubico/yubico-piv-tool/issues/393. This is something I'm looking into at the moment.

**Comment by qpernil** [comment]
This should be solved by https://github.com/Yubico/yubico-piv-tool/pull/399, are you able to test with a build from that branch ?

**Comment by TomasLoow** [comment]
That seems to solve the problem, yes. Thank you so much!

**Comment by qpernil** [comment]
The change has been merged to master and will be in the next official release. 
Thx for reporting !

**Comment by mouse07410** [comment]
> Also, Im curious @mouse07410 what problem exactly was it you thought was gone ? As far as I know ykcs11 reports `CKA_ALWAYS_AUTHENTICATE` properly, with the exception of for non-default policy imported keys on YubiKeys without metadata support.

@qpernil The problem was that `jarsigner` (and some other apps, but I reported `jarsigner` only as it's the most well-known ;) was unable to deal with logic of "you just authenticated successfully - now submit your PIN again" that YKCS11 enforced.

**Comment by qpernil** [comment]
> The problem was that jarsigner (and some other apps, but I reported jarsigner only as it's the most well-known ;) was 
> unable to deal with logic of "you just authenticated successfully - now submit your PIN again" that YKCS11 enforced.

@mouse07410 I'm not sure what you mean by enforce here - as discussed several times before ykcs11 simply provides the CKF_LOGIN_REQUIRED flag in token info (which is per token, by the specification), and also the CKA_ALWAYS_AUTH attribute (which is per object, hence per key). On top of those it also enforces that a session is logged in before keys can be used, which is what it should when the CKF_LOGIN_REQUIRED is set. It never asks for PIN. What specifically do you see as wrong with this ?

There is one issue with keys that do not require PIN at all - since the CKF_LOGIN_REQUIRED flag is per token an application can't ask the pkcs11 module if it should ask for PIN at all per key. We have to return as we do because otherwise applications wouldn't log in at all and the YubiKey would refuse to sign (assuming we removed the module enforcements. I have tested doing that with pkcs11-tool, and it then works fine for keys that don't require PIN but fails for others).

I'm happy to fix this behavior if you can provide me with more info. Specifically if I have missed anything in how the interaction between an application and a pkcs11 module works regarding PIN.

**Comment by qpernil** [comment]
@mouse07410 I was considering simply removing the enforcement of logged in status in the ykcs11 module, and letting the YubiKey handle that. But it would probably fail tests that expect the module to act according to the spec, which I interpret to say that if the CKF_LOGIN_REQUIRED is set then a call to C_Login is _required_. So this is a best effort to follow the spec.

In regards to CKA_ALWAYS_AUTH the module now uses attestations / metadata to determine how that flag should be reported. This can fail for imported keys with non-default PIN policy because older YubiKeys don't support the metadata command. If that happens it will fall back to using the default PIN policies, as a best effort. For generated keys this can't fail because keys that don't support attestation also don't support non-default PIN policies.

**Comment by qpernil** [comment]
> It was caused by ALWAYS_AUTHENTICATE property of the key in slot 9c. jarsigner failed to realize that the token required another login, and failed upon the error.

@mouse07410 assuming the key in 9c had the 'always' PIN policy (so that ALWAYS_AUTHENTICATE was TRUE) this sounds like an application error, does it not ? The application is required to perform a context-specific login before each signing operation in that case. There is no guarantee in general that a pkcs11 module doesn't perform any commands on the PIV application between the regular login and the second one. And any command would mean a new PIN verification would be required by the PIV spec. ykcs11 goes out of it's way not to touch the PIV application between actual operations, so this could work with it if we removed the enforcement in software, but in my opinion this would break compliance with the spec. 
To clear, this would allow an application to basically violate the pkcs11 spec (which is admittedly a _bit_ vague) and not perform the context-specific login directly after the normal login, but a new context specific login would still be required _by PIV_ after the first signature.
