### ISSUE TITLE
ec256  private key issue 

### ISSUE THREAD

**Issue by c3ph3us** [Yubico/yubico-piv-tool#89]
1) why i cant generate ecc keys on slot 9c/d

$ yubico-piv-tool -s 9a -A ECCP256 -a generate

     Enter management key: 
     -----BEGIN PUBLIC KEY-----
     MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEvNduKCh5H/OMBYNtiGVAfxQNlAMA
     kmXl2n7ttQt9W5k83NFWNWKShjh4zgfw4bvTV9myKBKBWD62ZkO5s5ZQhw==
     -----END PUBLIC KEY-----
     Successfully generated a new private key.

$ pkcs11-tool -v -O

     Using slot 0 with a present token (0x0)
     Data object 7140000
       label:          'Card Capability Container'
       application:    'Card Capability Container'
       app_id:         2.16.840.1.101.3.7.1.219.0
       flags:          <empty>

$ pkcs15-tool -v -k

     Using reader with a card: Yubico Yubikey NEO OTP+U2F+CCID 00 00
     Connecting to card in reader Yubico Yubikey NEO OTP+U2F+CCID 00 00...
     Using card driver PIV-II  for multiple cards.
     Trying to find a PKCS#15 compatible card...
     Found PIV_II!
     Card has 0 private key(s).

i also have following problems with pkcs11 

  https://github.com/OpenSC/pam_pkcs11/issues/23

i can generate ec key and cert with openssl but i cant use it either with ssh or pam pkcs11

2) why this tool allow to set MK without provide a default one ? 
3) why we can't set flag while generate private key / or import it ti device to allow export ? (example by provide MK key) ??
4) why this tool not providing options to show slot infos ? 
5) why i can add key when it is generated with -param_enc explicit  instead named_curve ?

 *explicit - tells openssl to embed the full parameters of the curve in the key, as opposed to just its name. This allows clients that are not aware of the specific curve name to work with it, at the cost of slightly increasing the size of the key (and the certificate)*

**Comment by a-dma** [comment]
1) To generate a key is slot 9c run `yubico-piv-tool -a verify -a generate -s 9c` (assuming you haven't changed the default management key) add something like `-A ECCP256` if you don't want an RSA key.

2) How did you get that idea? From the man page:
```
-k, --key[=STRING]       Management key to use
                             (default=`010203040506070801020304050607080102030405060708')
```
3) I thought we already discussed this in #76, you can't export private keys, ever.
4) `yubico-piv-tool -a status`
5) I am not sure what you mean there, are you talking about generating a key externally with OpenSSL and importing that using yubico-piv-tool? The following works just fine:
```
openssl ecparam -genkey -name prime256v1 -noout -out key.pem
yubico-piv-tool -a verify -a import-key -s 9a -i key.pem
```

Ad a general note, I'm under the impression that you expect something to show up in the status command after you have generated a key, that's not the case if all you have is a key and no certificate. The way PIV works is that you can only see certificates in a slot. The presence of a certificate assumes that the corresponding private key is also present. I suggest you have a look at the "Example Usage" section at https://developers.yubico.com/yubico-piv-tool/

**Comment by c3ph3us** [comment]
1/   
      - for slot 9a 9c i see keys !!!  they are listed 

    Using reader with a card: Yubico Yubikey NEO OTP+U2F+CCID 00 00
    Private EC Key [PIV AUTH key]
        Object Flags   : [0x1], private
        Usage          : [0x4], sign
        Access Flags   : [0x1D], sensitive, alwaysSensitive, neverExtract, local
        FieldLength    : 256
        Key ref        : 154 (0x9A)
        Native         : yes
        Auth ID        : 01
        ID             : 01
        MD:guid        : 0x' [cut]

      - for slot 9d 9e i don't see them 
   
2/ 
     - reset device 
     - u don't need to provide default key to setup new one :) 

3/ 
              Access Flags   : [0x1D], sensitive, alwaysSensitive, **neverExtract,** local

              why this flag could not be set to allow if MK provided ? 

4/   yubico-piv-tool -a status   
      shows only info related to cert not key as i provided you in 1/

5/ 
         if you so smart then generate key with -param_enc explicit and import to yubikey

**Comment by a-dma** [comment]
1) I assure you that there is no way of knowing whether or not a private key is present unless the corresponding certificate is also available. The PKCS#11 module knows about PIV object and shows them as data objects, but as you might have noticed it doesn't show a private o public key object unless there is a certificate loaded. Take the output of `yubico-piv-tool -a status` as reference.

2) I assume you're talking about using yubico-piv-tool now. You don't need to provide the default key because _it is the default key_. When one is not provided the tool uses the default value.

3) Because there is no way of extracting private keys from a YubiKey. And if that wasn't enough, there is also no specified way of extracting private keys in SP-800-73.

4) Exactly my point! I don't know what tool you're using there, but keep in mind that it's not uncommon for tools and agents to cache information. Again, I suggest that you use the output of yubico-piv-tool as reference.

5) Now I understand what you mean. You wrote *can* instead of *can't* in your previous message. The reason why that doesn't work is because what is parsed is the private key section of the file and not the EC parameters. If you don't specify `-param_enc explicit` you will get the private key and the OID of the curve in the same block. If instead you do specify that option, you will get the explicit values (as expected).
Just compare the output of
```
openssl ecparam -name prime256v1 -noout -genkey | openssl asn1parse
```
and
```
openssl ecparam -name prime256v1 -noout -genkey -param_enc explicit | openssl asn1parse
```
 The reason why this doesn't work is because, to the best of my knowledge, it is not possible to convert explicit parameters into a named curve in OpenSSL and hence to check whether or not the curve used is supported.

**Comment by c3ph3us** [comment]
@a-dma thanks for clarification 
sometimes the simplest things are forming misunderstandings - (see due to lack of a letter) especially when i think  that you know that i know :) example by use term "i see the keys" i  mean i see they presence :) 

i understand that cert and keys are generated by JVM and they software (applet)  = known as PIV  pksc11 engine on card ? what is blocking "me" as developer to overcome certain behaviors of card applet ? only that i don't have/know card management key - i did write to  Michael Poitner (from NXP) some time ago (about 3 years)  to grand access to yubico developer program  but with any respond and i gave up 

second i live in Europe and i don't give damn shit on **NIST** and what they have to say. 


you need to understand:
as a customer i want some functionality and if you want make cash you need to provide it to me.anything else doesn't care. ( to understand i like and i want 3 digit length pin :) 
i it is not prohibited by law and you are capable to do it why not ( this is a consumer expectation for product) ?  and if you will not provide it to me ill will find someone who will :) or 
or will someone appear who will do it and will make benefisant of it :)

what i expect from youbikey now:

1) be able to hold key and cert compatible with "anything/everything" - authentication,  signing ,ssl
2) have customizable CA on my card to sign certs  and 
3) have wrapped eg 3-DES key which i could take out from card !!! to perform others operations 
like usage with ecryptfs 
4) have possibility to export key to make backup copy 
 [ DON"T SAY WE CAN'T !!! - SEE PGP APPLET - THEY CAN :) ] 
5) and pleas look here https://github.com/OpenSC/pam_pkcs11/issues/23
6) manny more ...

**Comment by a-dma** [comment]
> i understand that cert and keys are generated by JVM and they software (applet) = known as PIV pksc11 engine on card ?

Well it depends, if you import the keys they are generated by whatever tool you decided to use, but if you tell the device to generate the private key for you they are actually generated internally and never leave the device.

> what is blocking "me" as developer to overcome certain behaviors of card applet ? only that i don't have/know card management key - i did write to Michael Poitner (from NXP) some time ago (about 3 years) to grand access to yubico developer program but with any respond and i gave up

That program is long gone. You're welcome to acquire NPX keys through their official channels and write your own application though.

> second i live in Europe and i don't give damn shit on NIST and what they have to say.

You're entitled to your own opinion, but since we're talking about an application based on a NIST standard, I would say that ignoring the specifications and NIST altogether might be a tad unwise.

> you need to understand:
as a customer i want some functionality and if you want make cash you need to provide it to me.anything else doesn't care. ( to understand i like and i want 3 digit length pin :) 
i it is not prohibited by law and you are capable to do it why not ( this is a consumer expectation for product) ? and if you will not provide it to me ill will find someone who will :) or 
or will someone appear who will do it and will make benefisant of it :)

I agree that as a customer you're entitled to having opinions and making requests, but we as a company are also free to make our own decisions. Unfortunately you can never make everybody happy, and we have to draw the line somewhere for what we deem reasonable/feasible or not.
Obviously, as you point out, you're free to find the solution that you need elsewhere.

> what i expect from youbikey now:
>
> 1) be able to hold key and cert compatible with "anything/everything" - authentication, signing ,ssl

You can load any kind of X.509 certificate onto the device, add your own extensions if you want, as long as it is not too large it will work. Algorithm-wise we're bound by the capabilities of the hardware.

> 2) have customizable CA on my card to sign certs and 

Have a look here https://developers.yubico.com/yubico-piv-tool/Certificate_Authority.html

> 3) have wrapped eg 3-DES key which i could take out from card !!! to perform others operations 
like usage with ecryptfs

At the cost of sounding like a broken record to you: it's not in the standard. This isn't Yubico's _encrypt'o'matic 3000_, but NIST's _SP-800-73_. We can't just add functionality at will, regardless of how much sense they make.

> 4) have possibility to export key to make backup copy 
[ DON"T SAY WE CAN'T !!! - SEE PGP APPLET - THEY CAN :) ] 

You might want to look again, the PGP applet can't do that either. If you're talking about the fact that you're asked to create a backup of the key during generation, you might be surprised to find out that if you say yes the key is generated locally and sent to the device, as opposed to being generated *on* the device itself. Big difference.

> 5) and pleas look here OpenSC/pam_pkcs11#23

Sorry but that is a different project, I won't intervene there.

> 6) manny more ...

Speaking of which, the discussion has (_for the second time_) gone wildly off-topic. This is an issue tracker for a specific project, not a wishlist for products nor a support systems.

I'd appreciate we could keep discussions here on-topic. If you want to discuss ideas and requests there is a forum or you're welcome to open a support ticket if you think that the product is not working as expected.

That being said, I will close this issue to prevent it from going even further off-topic.

**Comment by c3ph3us** [comment]
>That program is long gone. You're welcome to acquire NPX keys through their official channels and write your own application though.

how?

**Comment by a-dma** [comment]
As I said, you would have to go through NXP official channels. I've never done the procedure myself, I wouldn't know what it entails. Try asking them.

You can not emit a static password (or an OTP) without touch.
